updates

diff --git a/mqscripts/mqMonitor b/mqscripts/mqMonitor
--- a/mqscripts/mqMonitor
+++ b/mqscripts/mqMonitor
@@ -4,8 +4,10 @@
 #
 set +e
 #
-echo "Monitor: MQ Monitor     "
-echo "------------------------"
+echo "Monitor: MQ Monitor"
+echo "Monitor: Version 1.0.0.2"
+echo $(date)
+echo "---------------------------"
 echo "Monitor: MQMonitor is running as:  "
 id
 #
@@ -29,7 +31,7 @@ immediateStop()
 #
 # Remove Lock file
 #
-remoteLock() {
+removeLock() {
 	echo "Monitor: Removing Lock file"
 	rm /var/mqm/${IBM_MQ_QUEUEMANAGER}.lock
 }
@@ -52,87 +54,80 @@ createQueueManager()
 	echo "----------------------------------------"
 #
 	dspmq | grep ${IBM_MQ_QUEUEMANAGER}
-	qmgr_exists=`dspmq | grep ${IBM_MQ_QUEUEMANAGER} > /dev/null ; echo $?`
-	echo "Monitor: Queue Manager ${IBM_MQ_QUEUEMANAGER} exists = ${qmgr_exists}"
+	qmgrExists=`dspmq | grep ${IBM_MQ_QUEUEMANAGER} > /dev/null ; echo $?`
+	echo "Monitor: Queue Manager ${IBM_MQ_QUEUEMANAGER} exists = ${qmgrExists}"
 #
-# If we have NOT selected a 'COLD RESTART' of the queue manager, then create one
+	if [ ! -d /var/mqm/ ]; then
+	    mqFileSystem="N"
+	else
+	    mqFileSystem="Y"
+	fi
+	echo "Monitor: MQFileSystem is : ${mqFileSystem}"
 #
-	if [ ${COLD_QMGR} == "N" ]; then
-		if [ ${qmgr_exists} -ne 0 ]; then
+	if [ ${mqFileSystem} == "Y" ] && [ ${qmgrExists} -ne 0 ]; then
+	    coldRestart="Y"
+	else
+	    coldRestart="N"
+	fi
+	echo "Monitor: coldRestart is : ${coldRestart}"
+#
+# If we have NOT selected 'COLD RESTART',  then create 
+#    a new queue manager if it doesn't exist
+#
+	if [ ${coldRestart} == "N" ]; then
+		if [ ${qmgrExists} -ne 0 ]; then
 			echo "Monitor: Info: Creating queue manager ${IBM_MQ_QUEUEMANAGER}"
 			echo "Monitor: Current disk space / mount points"
 			df -h
 #
-# If we have NOT selected 'MULTI INSTANCE', then create a new queue manager, otherwise, 
-#     multi instance queue managers have 2 instances, active(0) and passive(1)
-#     When active(0) is selected, create the queue manager
-#     When passive(1)  
+			echo "Monitor: Creating queue manager ..."
+			crtmqm -u DEAD.LETTER.QUEUE -lc -lp ${IBM_MQ_PRIMARYLOGFILES} -ls ${IBM_MQ_SECONDARYLOGFILES} ${IBM_MQ_QUEUEMANAGER}
 #
-			if [ ${MULTI} == "N" ]; then
-				echo "Monitor: Creating queue manager ..."
-				crtmqm -u DEAD.LETTER.QUEUE -lc -lp ${IBM_MQ_PRIMARYLOGFILES} -ls ${IBM_MQ_SECONDARYLOGFILES} ${IBM_MQ_QUEUEMANAGER}
-			else
-#
-# If multi instance, we have 2 instances - active(0) and passive(1)
-#     When instance is active, check the file system, create the queue manager and show the MQ Info for the passive queue manager
-#
-				if [ ${INST} == "0" ]; then
-#
-# Check file system
-#
-                    . ./mqCheckFileSystem    
-#                   amqmfsck -f /var/mqm/qmgrs/${IBM_MQ_QUEUEMANAGER}
-					RC=$?
-					echo "RC=${RC}"
-					if [ ${RC} != 0 ]; then
-						echo "Monitor: File check failed for /var/mqm/qmgrs/${IBM_MQ_QUEUEMANAGER} : RC=${RC} "
-						exit
-					else
-						echo "Monitor: File check successful"
-					fi
-#
-# Create multi instance
-#
-					echo "Monitor: Creating multi-instance queue manager ..."
-					crtmqm -u DEAD.LETTER.QUEUE -lc -lp ${IBM_MQ_PRIMARYLOGFILES} -ls ${IBM_MQ_SECONDARYLOGFILES} ${IBM_MQ_QUEUEMANAGER}
-					dspmqinf -o command ${IBM_MQ_QUEUEMANAGER}
-				else
-#
-# Create the passive queue manager
-#
-					echo "Monitor: Adding multi instance"
-					addmqinf -s QueueManager -v Name=${IBM_MQ_QUEUEMANAGER} -v Directory=${IBM_MQ_QUEUEMANAGER} -v Prefix=/var/mqm -v DataPath=/var/mqm/qmgrs/${IBM_MQ_QUEUEMANAGER}
-				fi
-			fi
 			RC=$?
 			echo "RC=${RC}"
 			if [ ${RC} != 0 ]; then
 				echo "Monitor: Unable to create queue manager ${IBM_MQ_QUEUEMANAGER} "
 				exit
 			else
-				echo "Monitor: Queue manager ${IBM_MQ_QUEUEMANAGER} create cusscessfully, RET=${RC}"
+				echo "Monitor: Queue manager ${IBM_MQ_QUEUEMANAGER} create susscessfully, RET=${RC}"
 			fi
 #
-			if [ ${MULTI} == "N" ]; then
-				echo "Starting queue manager"
-				strmqm ${IBM_MQ_QUEUEMANAGER}
-			else
-				strmqm -x ${IBM_MQ_QUEUEMANAGER}
-			fi
-			RC=$?
-			echo "START RC=${RC}"
-			if [ ${RC} != 0 ]; then
-				echo "Monitor: Unable to start queue manager ${IBM_MQ_QUEUEMANAGER} "
-				exit
-			else
-				echo "Monitor: Queue manager ${IBM_MQ_QUEUEMANAGER} started cusscessfully, RET=${RC}"
-			fi			
-			sleep 5
+            webadmin
+#
+		    configPreRunningQueueManager
 #
 # Save a copy of the mqs.ini file, so we can reuse it in a cold restart
 #
 			cp /var/mqm/mqs.ini /var/mqm/qmgrs/${IBM_MQ_QUEUEMANAGER}/copy_mqs.in
-			configQueueManager
+#
+			echo "Monitor: Starting queue manager"
+			strmqm ${IBM_MQ_QUEUEMANAGER}
+			RC=$?
+			echo "Monitor: START RC=${RC}"
+			if [ ${RC} != 0 ]; then
+				echo "Monitor: Unable to start queue manager ${IBM_MQ_QUEUEMANAGER} "
+				exit
+			else
+				echo "Monitor: Queue manager ${IBM_MQ_QUEUEMANAGER} started successfully, RET=${RC}"
+			fi
+			echo "Monitor: Sleeping for 5 seconds"			
+			sleep 5
+#
+			configPostRunningQueueManager
+#
+		else
+		    echo "Monitor: Queue manager ${IBM_MQ_QUEUEMANAGER} already exists, attempting to restart"
+#
+			echo "Monitor: Starting queue manager"
+			strmqm ${IBM_MQ_QUEUEMANAGER}
+			RC=$?
+			echo "Monitor: START RC=${RC}"
+			if [ ${RC} != 0 ]; then
+				echo "Monitor: Unable to start queue manager ${IBM_MQ_QUEUEMANAGER} "
+				exit
+			else
+				echo "Monitor: Queue manager ${IBM_MQ_QUEUEMANAGER} started successfully, RET=${RC}"
+			fi
 #
 		fi
 	else
@@ -141,8 +136,8 @@ createQueueManager()
 #
 # Cold restart
 #
-		echo "Cold ReStart"
-		echo "Removing old log files for ... ${IBM_MQ_QUEUEMANAGER} in /var/mqm/logs"
+		echo "Monitor: Cold ReStart"
+		echo "Monitor: Removing old log files for ... ${IBM_MQ_QUEUEMANAGER} in /var/mqm/logs"
 		cd /var/mqm/log/${IBM_MQ_QUEUEMANAGER}/
 		rm -r *
 		ls -lrt 
@@ -156,7 +151,7 @@ createQueueManager()
 #        Messages stored on log files will be lost
 #    if every thing works, the queue manager should start sucessfully
 #
-		echo "Creating dummy queue manager ... COLD${IBM_MQ_QUEUEMANAGER}"
+		echo "Monitor: Creating dummy queue manager ... COLD${IBM_MQ_QUEUEMANAGER}"
 		crtmqm -u DEAD.LETTER.QUEUE -lc -lp ${IBM_MQ_PRIMARYLOGFILES} -ls ${IBM_MQ_SECONDARYLOGFILES} COLD${IBM_MQ_QUEUEMANAGER}
 		RC=$?
 		if [ ${RC} != 5 ]; then
@@ -166,59 +161,103 @@ createQueueManager()
 			exit
 		fi
 #
-		echo ""
-		echo "Copying new config file from COLD${IBM_MQ_QUEUEMANAGER} to ${IBM_MQ_QUEUEMANAGER}"
+		echo "***********************************"
+		echo "Monitor: Copying new config file from COLD${IBM_MQ_QUEUEMANAGER} to ${IBM_MQ_QUEUEMANAGER}"
 		mv /var/mqm/log/COLD${IBM_MQ_QUEUEMANAGER}/* /var/mqm/log/${IBM_MQ_QUEUEMANAGER} 
 		ls -lrt /var/mqm/log/${IBM_MQ_QUEUEMANAGER}
-		echo "Copying mqs.ini"
+		echo "Monitor: Copying mqs.ini"
 		cp /var/mqm/qmgrs/${IBM_MQ_QUEUEMANAGER}/copy_mqs.ini /var/mqm/mqs.ini
-		echo ""
+		echo "***********************************"
 #
 # Remove the 'dummy' queue manager
 #
 		dltmqm COLD${IBM_MQ_QUEUEMANAGER}
+#
+		echo "Monitor: Starting queue manager ${IBM_MQ_QUEUEMANAGER} after cold-restart"
+		strmqm ${IBM_MQ_QUEUEMANAGER}
+		RC=$?
+		echo "Monitor: START RC=${RC}"
+		if [ ${RC} != 0 ]; then
+			echo "Monitor: Unable to start queue manager ${IBM_MQ_QUEUEMANAGER} "
+			exit
+		else
+			echo "Monitor: Queue manager ${IBM_MQ_QUEUEMANAGER} started successfully, RET=${RC}"
+		fi
+
 	fi
 #
 	set +e
-	echo "Monitor: Starting queue manager ${IBM_MQ_QUEUEMANAGER}"
-	strmqm ${IBM_MQ_QUEUEMANAGER}
-	echo "Monitor: Queue manager ..."
-	RC=$?
-	if [ ${RC} != 5 ]; then
-		echo "Monitor: Queue manager is starting ${RC}"
-	else
-		echo "Monitor: Queue manager returned error code ${RC}"
+#	echo "Monitor: Starting queue manager ${IBM_MQ_QUEUEMANAGER}"
+#	strmqm ${IBM_MQ_QUEUEMANAGER}
+#	echo "Monitor: Queue manager ..."
+#	RC=$?
+#	if [ ${RC} != 5 ]; then
+#		echo "Monitor: Queue manager is starting ${RC}"
+#	else
+#		echo "Monitor: Queue manager returned error code ${RC}"
+#	fi
+#
+    echo "Monitor: Starting WebConsole"
+	strmqweb
+	dspmqweb
+#
+#	postConfigurations
+#
+    ps -ef | grep mq-metrics | grep -v grep
+	monitorRunning=`ps -ef | grep mq-metrics | grep -v grep | wc -l`
+	if [ ${monitorRunning} != 0 ]; then
+		echo "start service(MQMONITOR)" | runmqsc ${IBM_MQ_QUEUEMANAGER}
 	fi
-#
-	postConfigurations
-#
+	RC=$?
+	if [ ${RC} != 0 ]; then
+		echo "Monitor: MQMONITOR service did not start: ${RC}"
+	else
+		echo "Monitor: MQMONITOR service started successfully : ${RC}"
+	fi
+
 	set -e
 }
-
 #
-# Apply .MQSC configuration files to the queue manager
+# Pre Running Queue Manager config
 #
-configQueueManager()
+configPreRunningQueueManager()
 {
-	echo "Monitor: Applying configuration to queue manager using .mqsc files"
-	. ./mqSetupQueueManager
 #
     echo "Monitor: Creating / extracting keystore and certificate"
 	. ./mqCertificates
 #
 }
+#
+# Post Running Queue Manager config
+# Apply .MQSC configuration files to the queue manager
+#
+configPostRunningQueueManager()
+{
 
+	echo "Monitor: Setup monitor service in .mqsc files"
+	. ./mqSetupMonitorService ${IBM_MQ_QUEUEMANAGER}
+
+	echo "Monitor: Applying configuration to queue manager using .mqsc files"
+	. ./mqSetupQueueManager
+#
+#    echo "Monitor: Starting monitoring API"
+#	. ./mqRunQmgrMetrics ${IBM_MQ_QUEUEMANAGER}
+}
+#
+#
+webadmin() 
+{
+	echo "Monitor: Enabling MQWebBrowser"
+	. ./mqWebAdmin
+}
 #
 # Post configurations
 # Run after the queue manager has been started
 #
-postConfigurations() 
-{
-	echo "Monitor: Enabling MQWebBrowser"
-	. ./mqWebAdmin
+##postConfigurations() 
+##{
 #
-}
-
+##}
 #
 # Ensure that the queue manager is running
 #
@@ -278,14 +317,18 @@ monitor()
 }
 #
 trap stop SIGTERM SIGINT
-if [ -z ${COLD_QMGR} ]; then
-    echo "Monitor: MQ Creating queue manager"
-	COLD_QMGR="N"
-else
-    echo "Monitor: MQ Cold ReStart property is set as ${COLD_QMGR}"
-fi
+#if [ -z ${coldRestart} ]; then
+#    echo "Monitor: MQ Creating queue manager"
+#	coldRestart="N"
+#else
+#    echo "Monitor: MQ Cold ReStart property is set as ${coldRestart}"
+#fi
+#
+#echo "Switching users"
+#
 createQueueManager
 monitor
+#
 if [ "${wasrunningelsewhere}" == "true" ]; then
     echo "Monitor: Queue manager was running elsewhere, starting queue manager"
 	wasrunningelsewhere=false
